server:
  port: 8089

#local:
#  server:
#    port : 8084

spring:
  application:
    name: first
  profiles:
    include: oauth
  h2:
    console:
      enabled: true
  datasource:
    #url: jdbc:h2:mem:testdb
    url: jdbc:h2:tcp://localhost/~/test
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update # 서버 시작에 테이블 생성
      #ddl-auto: create # 서버 시작에 테이블 생성
    properties:
      hibernate:
        format_sql: true  # 압축된 쿼리를 읽기 좋게 포멧
  security:
    basic:
      enabled: false # security 기본 인증 옵션 제거
  devtools:
    livereload:
      enabled: true
  mustache:
    cache: false
  mvc:
    static-path-pattern: /static/**
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout:
      seconds: 900
logging:
  level:
    org:
      hibernate:
        SQL: debug  # 로그 형식으로 쿼리 보여주기