server:
  port: 8089

#local:
#  server:
#    port : 8084

spring:
  application:
    name: first
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create # 서버 시작에 테이블 생성
    properties:
      hibernate:
        format_sql: true  # 압축된 쿼리를 읽기 좋게 포멧

logging:
  level:
    org:
      hibernate:
        SQL: debug  # 로그 형식으로 쿼리 보여주기